2025-05-25 12:52:55,574 ERROR: Exception on /v1/users/ [POST] [in D:\Projetos\pp-case-api\venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "D:\Projetos\pp-case-api\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projetos\pp-case-api\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projetos\pp-case-api\venv\Lib\site-packages\flask_restx\api.py", line 402, in wrapper
    resp = resource(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projetos\pp-case-api\venv\Lib\site-packages\flask\views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projetos\pp-case-api\venv\Lib\site-packages\flask_restx\resource.py", line 41, in dispatch_request
    resp = meth(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projetos\pp-case-api\venv\Lib\site-packages\flask_restx\marshalling.py", line 244, in wrapper
    resp = f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "D:\Projetos\pp-case-api\venv\Lib\site-packages\flask_jwt_extended\view_decorators.py", line 167, in decorator
    verify_jwt_in_request(
  File "D:\Projetos\pp-case-api\venv\Lib\site-packages\flask_jwt_extended\view_decorators.py", line 94, in verify_jwt_in_request
    jwt_data, jwt_header, jwt_location = _decode_jwt_from_request(
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projetos\pp-case-api\venv\Lib\site-packages\flask_jwt_extended\view_decorators.py", line 358, in _decode_jwt_from_request
    raise NoAuthorizationError(errors[0])
flask_jwt_extended.exceptions.NoAuthorizationError: Missing Authorization Header
2025-05-25 12:58:16,814 INFO: Flask CRUD startup [in D:\Projetos\pp-case-api\app.py:29]
2025-05-25 13:32:22,592 INFO: Flask CRUD startup [in D:\Projetos\pp-case-api\app.py:29]
2025-05-25 13:33:41,821 INFO: Flask CRUD startup [in D:\Projetos\pp-case-api\app.py:29]
2025-05-25 13:33:45,928 ERROR: Erro interno do servidor: 'NoneType' object has no attribute 'id' [in D:\Projetos\pp-case-api\app.py:56]
Traceback (most recent call last):
  File "D:\Projetos\pp-case-api\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projetos\pp-case-api\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projetos\pp-case-api\auth.py", line 33, in login
    access_token = create_access_token(identity=user.id)
                                                ^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'
2025-05-25 13:34:37,530 INFO: Flask CRUD startup [in D:\Projetos\pp-case-api\app.py:29]
2025-05-25 13:34:40,542 ERROR: Erro interno do servidor: create_access_token() missing 1 required positional argument: 'identity' [in D:\Projetos\pp-case-api\app.py:56]
Traceback (most recent call last):
  File "D:\Projetos\pp-case-api\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projetos\pp-case-api\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projetos\pp-case-api\auth.py", line 33, in login
    access_token = create_access_token()
                   ^^^^^^^^^^^^^^^^^^^^^
TypeError: create_access_token() missing 1 required positional argument: 'identity'
2025-05-25 13:34:56,619 INFO: Flask CRUD startup [in D:\Projetos\pp-case-api\app.py:29]
2025-05-25 13:35:50,890 ERROR: Erro interno do servidor na API: Missing 'Bearer' type in 'Authorization' header. Expected 'Authorization: Bearer <JWT>' [in D:\Projetos\pp-case-api\routes.py:74]
Traceback (most recent call last):
  File "D:\Projetos\pp-case-api\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projetos\pp-case-api\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projetos\pp-case-api\venv\Lib\site-packages\flask_restx\api.py", line 402, in wrapper
    resp = resource(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projetos\pp-case-api\venv\Lib\site-packages\flask\views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projetos\pp-case-api\venv\Lib\site-packages\flask_restx\resource.py", line 41, in dispatch_request
    resp = meth(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projetos\pp-case-api\venv\Lib\site-packages\flask_restx\marshalling.py", line 244, in wrapper
    resp = f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "D:\Projetos\pp-case-api\venv\Lib\site-packages\flask_jwt_extended\view_decorators.py", line 167, in decorator
    verify_jwt_in_request(
  File "D:\Projetos\pp-case-api\venv\Lib\site-packages\flask_jwt_extended\view_decorators.py", line 94, in verify_jwt_in_request
    jwt_data, jwt_header, jwt_location = _decode_jwt_from_request(
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projetos\pp-case-api\venv\Lib\site-packages\flask_jwt_extended\view_decorators.py", line 358, in _decode_jwt_from_request
    raise NoAuthorizationError(errors[0])
flask_jwt_extended.exceptions.NoAuthorizationError: Missing 'Bearer' type in 'Authorization' header. Expected 'Authorization: Bearer <JWT>'
2025-05-25 13:35:50,924 ERROR: Exception on /v1/users/ [POST] [in D:\Projetos\pp-case-api\venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "D:\Projetos\pp-case-api\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projetos\pp-case-api\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projetos\pp-case-api\venv\Lib\site-packages\flask_restx\api.py", line 402, in wrapper
    resp = resource(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projetos\pp-case-api\venv\Lib\site-packages\flask\views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projetos\pp-case-api\venv\Lib\site-packages\flask_restx\resource.py", line 41, in dispatch_request
    resp = meth(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projetos\pp-case-api\venv\Lib\site-packages\flask_restx\marshalling.py", line 244, in wrapper
    resp = f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "D:\Projetos\pp-case-api\venv\Lib\site-packages\flask_jwt_extended\view_decorators.py", line 167, in decorator
    verify_jwt_in_request(
  File "D:\Projetos\pp-case-api\venv\Lib\site-packages\flask_jwt_extended\view_decorators.py", line 94, in verify_jwt_in_request
    jwt_data, jwt_header, jwt_location = _decode_jwt_from_request(
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projetos\pp-case-api\venv\Lib\site-packages\flask_jwt_extended\view_decorators.py", line 358, in _decode_jwt_from_request
    raise NoAuthorizationError(errors[0])
flask_jwt_extended.exceptions.NoAuthorizationError: Missing 'Bearer' type in 'Authorization' header. Expected 'Authorization: Bearer <JWT>'
